baseurl = "https://softlayer.github.io/"
languageCode = "en-us"
title = "SoftLayer API Examples"
canonifyurls = true
SectionPagesMenu = "sections"
pygmentsuseclasses = false
pluralizelisttitles = "false"
paginate = 10
googleAnalytics = "UA-88235803-1"
disablePathToLower = false


[params]
  description = "SoftLayer API Examples, implementations, and release notes."
  author = "SoftLayer"


[taxonomies]
	tag = "tags"
	class = "classes"

pluralizeListTitles = false

[[menu.main]]
    name = "go"
    identifier = "go"
    url = "/go/"
[[menu.main]]
    name = "perl"
    identifier = "perl"
    url = "/perl/"
[[menu.main]]
    name = "php"
    identifier = "php"
    url = "/php/"
[[menu.main]]
    name = "python"
    identifier = "python"
    url = "/python/"
[[menu.main]]
    name = "ruby"
    identifier = "ruby"
    url = "/ruby/"
[[menu.main]]
	name = "rest"
	identifier = "rest"
	url = "/rest/"
[[menu.main]]
    name = "tools"
    identifier = "tools"
    url = "/tools/"
